export const SOURCES = [
  // =========================================================
  // 1) IN-REGION: MIDDLE EAST / ARAB WORLD
  // =========================================================
  {
    name: "Arab Center for Research and Policy Studies",
    nameAr: "المركز العربي للأبحاث ودراسة السياسات",
    method: "html",
    url: "https://www.dohainstitute.org/ar/ResearchAndStudies/Pages/default.aspx",
    lang: "ar",
    regionFocus: "mena",
    base: "in-region",
    category: "research-center",
    freq: "periodic",
    topics: ["politics", "governance", "economy", "culture"],
    focusKeywords: ["العالم العربي", "الشرق الأوسط", "سياسة", "اقتصاد", "ثقافة"]
  },
  {
    name: "Doha Institute for Graduate Studies",
    nameAr: "معهد الدوحة للدراسات العليا",
    method: "html",
    url: "https://www.dohainstitute.edu.qa/en/Research/Pages/default.aspx",
    lang: "en",
    regionFocus: "mena",
    base: "in-region",
    category: "university-center",
    freq: "periodic",
    topics: ["politics", "culture", "society", "governance"],
    focusKeywords: ["middle east", "arab", "gulf", "culture", "society"]
  },
  {
    name: "Al Jazeera Centre for Studies",
    nameAr: "مركز الجزيرة للدراسات",
    method: "rss",
    url: "https://studies.aljazeera.net/ar/rss",
    lang: "ar",
    regionFocus: "mena",
    base: "in-region",
    category: "think-tank",
    freq: "periodic",
    topics: ["politics", "geopolitics", "media", "culture"],
    focusKeywords: ["الشرق الأوسط", "العالم العربي", "أفريقيا", "الخليج", "المغرب العربي"]
  },
  {
    name: "Middle East Council on Global Affairs",
    nameAr: "مجلس الشرق الأوسط للشؤون العالمية",
    method: "html",
    url: "https://mecouncil.org/publications/",
    lang: "en",
    regionFocus: "mena",
    base: "in-region",
    category: "think-tank",
    freq: "periodic",
    topics: ["politics", "economy", "security", "geopolitics"],
    focusKeywords: ["middle east", "arab", "gulf", "north africa"]
  },
  {
    name: "Carnegie Middle East Center",
    nameAr: "كارنيغي الشرق الأوسط",
    method: "rss",
    url: "https://carnegie-mec.org/rss/solr.xml",
    lang: "ar",
    regionFocus: "mena",
    base: "in-region",
    category: "think-tank",
    freq: "periodic",
    topics: ["politics", "governance", "rights", "economy"],
    focusKeywords: ["سوريا", "لبنان", "العراق", "فلسطين", "الشرق الأوسط"]
  },
  {
    name: "Issam Fares Institute - AUB",
    nameAr: "معهد عصام فارس - الجامعة الأمريكية في بيروت",
    method: "html",
    url: "https://www.aub.edu.lb/ifi/Pages/default.aspx",
    lang: "en",
    regionFocus: "mena",
    base: "in-region",
    category: "university-center",
    freq: "periodic",
    topics: ["public-policy", "governance", "economy", "society"],
    focusKeywords: ["lebanon", "middle east", "arab", "public policy"]
  },
  {
    name: "Asfari Institute for Civil Society and Citizenship - AUB",
    nameAr: "معهد الأصفري للمجتمع المدني والمواطنة",
    method: "html",
    url: "https://website.aub.edu.lb/asfari/Pages/default.aspx",
    lang: "en",
    regionFocus: "mena",
    base: "in-region",
    category: "university-center",
    freq: "periodic",
    topics: ["society", "rights", "governance", "culture"],
    focusKeywords: ["civil society", "citizenship", "arab", "middle east"]
  },
  {
    name: "Center for Arab and Middle Eastern Studies - AUB",
    nameAr: "مركز الدراسات العربية والشرق أوسطية - AUB",
    method: "html",
    url: "https://www.aub.edu.lb/fas/cames/Pages/default.aspx",
    lang: "en",
    regionFocus: "mena",
    base: "in-region",
    category: "university-center",
    freq: "periodic",
    topics: ["culture", "history", "society", "politics"],
    focusKeywords: ["arab", "middle east", "society", "history"]
  },
  {
    name: "King Faisal Center for Research and Islamic Studies",
    nameAr: "مركز الملك فيصل للبحوث والدراسات الإسلامية",
    method: "html",
    url: "https://www.kfcris.com/en/publications",
    lang: "en",
    regionFocus: "mena",
    base: "in-region",
    category: "research-center",
    freq: "periodic",
    topics: ["politics", "culture", "history", "economy"],
    focusKeywords: ["arab", "gulf", "saudi", "middle east", "islamic studies"]
  },
  {
    name: "Emirates Center for Strategic Studies and Research",
    nameAr: "مركز الإمارات للدراسات والبحوث الاستراتيجية",
    method: "html",
    url: "https://www.ecssr.ae/en/publications/",
    lang: "en",
    regionFocus: "mena",
    base: "in-region",
    category: "research-center",
    freq: "periodic",
    topics: ["security", "geopolitics", "economy", "politics"],
    focusKeywords: ["gulf", "middle east", "arab", "security", "energy"]
  },
  {
    name: "Future for Advanced Research and Studies",
    nameAr: "مركز المستقبل للأبحاث والدراسات المتقدمة",
    method: "html",
    url: "https://futureuae.com/en-US/Mainpage/Items",
    lang: "en",
    regionFocus: "mena",
    base: "in-region",
    category: "research-center",
    freq: "periodic",
    topics: ["politics", "security", "economy", "technology"],
    focusKeywords: ["middle east", "arab", "gulf", "africa"]
  },
  {
    name: "Policy Center for the New South",
    nameAr: "مركز السياسات من أجل الجنوب الجديد",
    method: "rss",
    url: "https://www.policycenter.ma/rss.xml",
    lang: "en",
    regionFocus: "mena",
    base: "in-region",
    category: "think-tank",
    freq: "periodic",
    topics: ["economy", "geopolitics", "governance", "africa"],
    focusKeywords: ["morocco", "maghreb", "africa", "middle east", "sahel"]
  },
  {
    name: "Institut Royal des Études Stratégiques",
    nameAr: "المعهد الملكي للدراسات الاستراتيجية",
    method: "html",
    url: "https://www.ires.ma/publications/",
    lang: "fr",
    regionFocus: "mena",
    base: "in-region",
    category: "research-center",
    freq: "periodic",
    topics: ["strategy", "economy", "society", "geopolitics"],
    focusKeywords: ["maroc", "maghreb", "afrique", "monde arabe"]
  },
  {
    name: "OCP Policy Center Archive",
    nameAr: "أرشيف OCP Policy Center",
    method: "html",
    url: "https://www.policycenter.ma/publications",
    lang: "en",
    regionFocus: "mena",
    base: "in-region",
    category: "think-tank",
    freq: "periodic",
    topics: ["economy", "agriculture", "development", "africa"],
    focusKeywords: ["morocco", "africa", "development", "policy"]
  },
  {
    name: "Arab Thought Foundation",
    nameAr: "مؤسسة الفكر العربي",
    method: "html",
    url: "https://www.arabthought.org/ar/research-center",
    lang: "ar",
    regionFocus: "mena",
    base: "in-region",
    category: "foundation",
    freq: "annual",
    topics: ["culture", "education", "society", "identity"],
    focusKeywords: ["ثقافة", "تعليم", "مجتمع", "العالم العربي"]
  },
  {
    name: "Center for Arab Unity Studies",
    nameAr: "مركز دراسات الوحدة العربية",
    method: "html",
    url: "https://caus.org.lb/publications/",
    lang: "ar",
    regionFocus: "mena",
    base: "in-region",
    category: "research-center",
    freq: "periodic",
    topics: ["politics", "economy", "society", "culture"],
    focusKeywords: ["الوطن العربي", "قضايا عربية", "تنمية", "ثقافة"]
  },
  {
    name: "Tunisian Institute for Strategic Studies",
    nameAr: "المعهد التونسي للدراسات الاستراتيجية",
    method: "html",
    url: "https://www.ites.tn/publications/",
    lang: "fr",
    regionFocus: "mena",
    base: "in-region",
    category: "research-center",
    freq: "periodic",
    topics: ["strategy", "governance", "economy", "society"],
    focusKeywords: ["tunisie", "maghreb", "afrique", "monde arabe"]
  },
  {
    name: "Palestinian Center for Policy and Survey Research",
    nameAr: "المركز الفلسطيني للبحوث السياسية والمسحية",
    method: "html",
    url: "https://www.pcpsr.org/en/publications",
    lang: "en",
    regionFocus: "mena",
    base: "in-region",
    category: "research-center",
    freq: "periodic",
    topics: ["politics", "public-opinion", "governance"],
    focusKeywords: ["palestine", "gaza", "west bank", "middle east"]
  },
  {
    name: "Al-Shabaka - Palestinian Policy Network",
    nameAr: "الشبكة - شبكة السياسات الفلسطينية",
    method: "rss",
    url: "https://al-shabaka.org/feed/",
    lang: "en",
    regionFocus: "mena",
    base: "in-region",
    category: "policy-network",
    freq: "periodic",
    topics: ["politics", "rights", "culture", "society"],
    focusKeywords: ["palestine", "palestinian", "arab", "middle east"]
  },

  // =========================================================
  // 2) IN-AFRICA: AFRICAN UNIVERSITIES / CENTERS / THINK TANKS
  // =========================================================
  {
    name: "ISS Africa",
    nameAr: "معهد الدراسات الأمنية في أفريقيا",
    method: "rss",
    url: "https://issafrica.org/iss-today/feed",
    lang: "en",
    regionFocus: "africa",
    base: "in-africa",
    category: "think-tank",
    freq: "periodic",
    topics: ["security", "peace", "governance", "geopolitics"],
    focusKeywords: ["africa", "sahel", "horn of africa", "african union"]
  },
  {
    name: "SAIIA",
    nameAr: "معهد جنوب أفريقيا للشؤون الدولية",
    method: "html",
    url: "https://saiia.org.za/publications/",
    lang: "en",
    regionFocus: "africa",
    base: "in-africa",
    category: "think-tank",
    freq: "periodic",
    topics: ["governance", "economy", "international", "security"],
    focusKeywords: ["africa", "south africa", "regional", "governance"]
  },
  {
    name: "ACCORD",
    nameAr: "أكورد لحل النزاعات",
    method: "rss",
    url: "https://www.accord.org.za/feed/",
    lang: "en",
    regionFocus: "africa",
    base: "in-africa",
    category: "research-center",
    freq: "periodic",
    topics: ["peace", "security", "governance"],
    focusKeywords: ["africa", "conflict", "peacebuilding", "mediation"]
  },
  {
    name: "Afrobarometer Dispatches",
    nameAr: "أفروباروميتر - تقارير Dispatches",
    method: "html",
    url: "https://www.afrobarometer.org/dispatches/",
    lang: "en",
    regionFocus: "africa",
    base: "in-africa",
    category: "research-network",
    freq: "periodic",
    topics: ["public-opinion", "governance", "economy", "society"],
    focusKeywords: ["africa", "democracy", "governance", "society"]
  },
  {
    name: "CODESRIA",
    nameAr: "مجلس تطوير البحث الاجتماعي في أفريقيا",
    method: "html",
    url: "https://codesria.org/publications/",
    lang: "en",
    regionFocus: "africa",
    base: "in-africa",
    category: "university-network",
    freq: "periodic",
    topics: ["society", "culture", "governance", "economy"],
    focusKeywords: ["africa", "african studies", "social sciences"]
  },
  {
    name: "IPSS Addis Ababa University",
    nameAr: "معهد دراسات السلام والأمن - جامعة أديس أبابا",
    method: "html",
    url: "https://ipss-addis.org/publications/",
    lang: "en",
    regionFocus: "africa",
    base: "in-africa",
    category: "university-center",
    freq: "periodic",
    topics: ["peace", "security", "governance"],
    focusKeywords: ["ethiopia", "horn of africa", "peace", "security"]
  },
  {
    name: "Makerere Institute of Social Research",
    nameAr: "معهد البحوث الاجتماعية - جامعة ماكيريري",
    method: "html",
    url: "https://misr.mak.ac.ug/publications/",
    lang: "en",
    regionFocus: "africa",
    base: "in-africa",
    category: "university-center",
    freq: "periodic",
    topics: ["society", "culture", "politics", "economy"],
    focusKeywords: ["africa", "uganda", "society", "politics"]
  },
  {
    name: "University of Cape Town - ACJR",
    nameAr: "جامعة كيب تاون - مركز العدالة والمصالحة",
    method: "html",
    url: "https://www.justiceandreconciliation.org/publications/",
    lang: "en",
    regionFocus: "africa",
    base: "in-africa",
    category: "university-center",
    freq: "periodic",
    topics: ["rights", "peace", "governance"],
    focusKeywords: ["africa", "justice", "reconciliation", "transition"]
  },
  {
    name: "Wits School of Governance",
    nameAr: "كلية الحوكمة - جامعة ويتس",
    method: "html",
    url: "https://www.wits.ac.za/wsg/publications/",
    lang: "en",
    regionFocus: "africa",
    base: "in-africa",
    category: "university-center",
    freq: "periodic",
    topics: ["governance", "public-policy", "economy"],
    focusKeywords: ["africa", "governance", "public policy"]
  },
  {
    name: "CDD-Ghana",
    nameAr: "مركز التنمية الديمقراطية - غانا",
    method: "html",
    url: "https://cddgh.org/publications/",
    lang: "en",
    regionFocus: "africa",
    base: "in-africa",
    category: "research-center",
    freq: "periodic",
    topics: ["democracy", "governance", "public-opinion"],
    focusKeywords: ["ghana", "africa", "democracy", "governance"]
  },
  {
    name: "IPAR Senegal",
    nameAr: "المعهد المستقبلي الأفريقي - السنغال",
    method: "html",
    url: "https://ipar.sn/publications/",
    lang: "fr",
    regionFocus: "africa",
    base: "in-africa",
    category: "think-tank",
    freq: "periodic",
    topics: ["governance", "economy", "development"],
    focusKeywords: ["senegal", "afrique", "développement", "gouvernance"]
  },
  {
    name: "Kofi Annan International Peacekeeping Training Centre",
    nameAr: "مركز كوفي عنان للتدريب على حفظ السلام",
    method: "html",
    url: "https://www.kaiptc.org/publications/",
    lang: "en",
    regionFocus: "africa",
    base: "in-africa",
    category: "research-center",
    freq: "periodic",
    topics: ["peace", "security", "governance"],
    focusKeywords: ["africa", "peacekeeping", "security", "west africa"]
  },
  {
    name: "Institute for Global Dialogue",
    nameAr: "معهد الحوار العالمي",
    method: "html",
    url: "https://igd.org.za/publications/",
    lang: "en",
    regionFocus: "africa",
    base: "in-africa",
    category: "think-tank",
    freq: "periodic",
    topics: ["foreign-policy", "governance", "international"],
    focusKeywords: ["africa", "global south", "foreign policy"]
  },
  {
    name: "Institute of Development Studies - Nairobi",
    nameAr: "معهد دراسات التنمية - نيروبي",
    method: "html",
    url: "https://ids.uonbi.ac.ke/research-publications",
    lang: "en",
    regionFocus: "africa",
    base: "in-africa",
    category: "university-center",
    freq: "periodic",
    topics: ["development", "economy", "society"],
    focusKeywords: ["kenya", "africa", "development", "policy"]
  },
  {
    name: "AERC",
    nameAr: "اتحاد البحوث الاقتصادية الأفريقية",
    method: "html",
    url: "https://aercafrica.org/publications/",
    lang: "en",
    regionFocus: "africa",
    base: "in-africa",
    category: "research-network",
    freq: "periodic",
    topics: ["economy", "development", "public-policy"],
    focusKeywords: ["africa", "economic research", "development"]
  },
  {
    name: "African Leadership Centre",
    nameAr: "مركز القيادة الأفريقية",
    method: "html",
    url: "https://alcafricacenter.org/publications/",
    lang: "en",
    regionFocus: "africa",
    base: "in-africa",
    category: "research-center",
    freq: "periodic",
    topics: ["peace", "security", "leadership"],
    focusKeywords: ["africa", "peace", "security", "leadership"]
  },
  {
    name: "Institute for Peace and Security Studies",
    nameAr: "معهد السلام والأمن",
    method: "html",
    url: "https://ipss-addis.org/publications/",
    lang: "en",
    regionFocus: "africa",
    base: "in-africa",
    category: "university-center",
    freq: "periodic",
    topics: ["peace", "security", "governance"],
    focusKeywords: ["africa", "peace", "security"]
  },

  // =========================================================
  // 3) OUTSIDE REGION BUT FOCUSED ON MENA / ARAB STUDIES
  // =========================================================
  {
    name: "Harvard Center for Middle Eastern Studies",
    nameAr: "مركز هارفارد للدراسات الشرق أوسطية",
    method: "html",
    url: "https://cmes.fas.harvard.edu/cmes-publications",
    lang: "en",
    regionFocus: "mena",
    base: "outside",
    category: "university-center",
    freq: "periodic",
    topics: ["history", "culture", "politics", "society"],
    focusKeywords: ["middle east", "arab", "islamic", "mena"]
  },
  {
    name: "Georgetown CCAS",
    nameAr: "مركز جورجتاون للدراسات العربية المعاصرة",
    method: "html",
    url: "https://ccas.georgetown.edu/resources/",
    lang: "en",
    regionFocus: "mena",
    base: "outside",
    category: "university-center",
    freq: "periodic",
    topics: ["arab-studies", "politics", "culture", "society"],
    focusKeywords: ["arab", "middle east", "sudan", "palestine"]
  },
  {
    name: "Columbia Middle East Institute",
    nameAr: "معهد كولومبيا للشرق الأوسط",
    method: "html",
    url: "https://middleeast.columbia.edu/content/publications",
    lang: "en",
    regionFocus: "mena",
    base: "outside",
    category: "university-center",
    freq: "periodic",
    topics: ["culture", "history", "politics", "society"],
    focusKeywords: ["middle east", "arab", "north africa"]
  },
  {
    name: "UCLA Center for Near Eastern Studies",
    nameAr: "مركز UCLA للدراسات الشرق الأدنى",
    method: "html",
    url: "https://international.ucla.edu/cnes/publications",
    lang: "en",
    regionFocus: "mena",
    base: "outside",
    category: "university-center",
    freq: "periodic",
    topics: ["culture", "history", "politics"],
    focusKeywords: ["near east", "middle east", "arab"]
  },
  {
    name: "Michigan CMENAS",
    nameAr: "مركز ميشيغان لدراسات الشرق الأوسط وشمال أفريقيا",
    method: "html",
    url: "https://ii.umich.edu/ii/cmenas/news-events/publications.html",
    lang: "en",
    regionFocus: "mena",
    base: "outside",
    category: "university-center",
    freq: "periodic",
    topics: ["culture", "society", "politics"],
    focusKeywords: ["mena", "middle east", "north africa", "arab"]
  },
  {
    name: "SOAS Middle East Institute",
    nameAr: "معهد الشرق الأوسط - SOAS",
    method: "html",
    url: "https://www.soas.ac.uk/middle-east-institute/publications",
    lang: "en",
    regionFocus: "mena",
    base: "outside",
    category: "university-center",
    freq: "periodic",
    topics: ["politics", "culture", "history", "economy"],
    focusKeywords: ["middle east", "arab", "north africa"]
  },
  {
    name: "Oxford Middle East Centre",
    nameAr: "مركز أكسفورد للشرق الأوسط",
    method: "html",
    url: "https://www.sant.ox.ac.uk/research/centres-and-programmes/middle-east-centre/publications",
    lang: "en",
    regionFocus: "mena",
    base: "outside",
    category: "university-center",
    freq: "periodic",
    topics: ["history", "politics", "society"],
    focusKeywords: ["middle east", "arab", "gulf", "maghreb"]
  },
  {
    name: "LSE Middle East Centre",
    nameAr: "مركز الشرق الأوسط - LSE",
    method: "html",
    url: "https://www.lse.ac.uk/middle-east-centre/publications",
    lang: "en",
    regionFocus: "mena",
    base: "outside",
    category: "university-center",
    freq: "periodic",
    topics: ["politics", "economy", "society", "culture"],
    focusKeywords: ["middle east", "north africa", "arab", "gulf"]
  },
  {
    name: "Middle East Institute",
    nameAr: "معهد الشرق الأوسط",
    method: "rss",
    url: "https://mei.edu/rss.xml",
    lang: "en",
    regionFocus: "mena",
    base: "outside",
    category: "think-tank",
    freq: "periodic",
    topics: ["politics", "economy", "culture", "security"],
    focusKeywords: ["middle east", "arab", "north africa", "gulf"]
  },
  {
    name: "Washington Institute for Near East Policy",
    nameAr: "معهد واشنطن لسياسة الشرق الأدنى",
    method: "html",
    url: "https://www.washingtoninstitute.org/policy-analysis",
    lang: "en",
    regionFocus: "mena",
    base: "outside",
    category: "think-tank",
    freq: "periodic",
    topics: ["security", "politics", "geopolitics"],
    focusKeywords: ["middle east", "near east", "iran", "gulf", "arab"]
  },
  {
    name: "MERIP",
    nameAr: "مشروع معلومات الشرق الأوسط",
    method: "rss",
    url: "https://merip.org/feed/",
    lang: "en",
    regionFocus: "mena",
    base: "outside",
    category: "research-platform",
    freq: "periodic",
    topics: ["politics", "rights", "culture", "political-economy"],
    focusKeywords: ["middle east", "arab", "palestine", "gaza", "north africa"]
  },
  {
    name: "POMEPS",
    nameAr: "مشروع علوم الشرق الأوسط السياسية",
    method: "rss",
    url: "https://pomeps.org/feed",
    lang: "en",
    regionFocus: "mena",
    base: "outside",
    category: "academic-network",
    freq: "periodic",
    topics: ["politics", "governance", "society"],
    focusKeywords: ["middle east", "arab", "authoritarianism", "protest"]
  },
  {
    name: "TIMEP",
    nameAr: "معهد التحرير لسياسة الشرق الأوسط",
    method: "rss",
    url: "https://timep.org/feed/",
    lang: "en",
    regionFocus: "mena",
    base: "outside",
    category: "think-tank",
    freq: "periodic",
    topics: ["rights", "governance", "politics"],
    focusKeywords: ["middle east", "egypt", "sudan", "arab", "justice"]
  },
  {
    name: "Arab Reform Initiative",
    nameAr: "مبادرة الإصلاح العربي",
    method: "rss",
    url: "https://www.arab-reform.net/feed/",
    lang: "en",
    regionFocus: "mena",
    base: "outside",
    category: "research-network",
    freq: "periodic",
    topics: ["governance", "rights", "economy", "politics"],
    focusKeywords: ["arab", "middle east", "north africa", "reform"]
  },
  {
    name: "GIGA Institute for Middle East Studies",
    nameAr: "معهد GIGA للدراسات الشرق أوسطية",
    method: "html",
    url: "https://www.giga-hamburg.de/en/the-giga/institutes/giga-institute-for-middle-east-studies",
    lang: "en",
    regionFocus: "mena",
    base: "outside",
    category: "research-center",
    freq: "periodic",
    topics: ["politics", "economy", "society", "geopolitics"],
    focusKeywords: ["middle east", "mena", "north africa", "arab"]
  },
  {
    name: "SWP Berlin - Middle East and Africa",
    nameAr: "المعهد الألماني للشؤون الدولية - الشرق الأوسط وأفريقيا",
    method: "html",
    url: "https://www.swp-berlin.org/en/topics/middle-east-and-africa",
    lang: "en",
    regionFocus: "mena",
    base: "outside",
    category: "think-tank",
    freq: "periodic",
    topics: ["security", "geopolitics", "politics"],
    focusKeywords: ["middle east", "north africa", "arab", "gulf"]
  },
  {
    name: "Chatham House MENA Programme",
    nameAr: "تشاتام هاوس - برنامج الشرق الأوسط وشمال أفريقيا",
    method: "html",
    url: "https://www.chathamhouse.org/regions/middle-east-and-north-africa",
    lang: "en",
    regionFocus: "mena",
    base: "outside",
    category: "think-tank",
    freq: "periodic",
    topics: ["politics", "economy", "security", "society"],
    focusKeywords: ["middle east", "north africa", "gulf", "arab"]
  },
  {
    name: "Brookings Center for Middle East Policy",
    nameAr: "بروكينغز - مركز سياسة الشرق الأوسط",
    method: "html",
    url: "https://www.brookings.edu/centers/center-for-middle-east-policy/",
    lang: "en",
    regionFocus: "mena",
    base: "outside",
    category: "think-tank",
    freq: "periodic",
    topics: ["politics", "governance", "economy"],
    focusKeywords: ["middle east", "arab", "north africa", "gulf"]
  },
  {
    name: "CSIS Middle East Program",
    nameAr: "CSIS - برنامج الشرق الأوسط",
    method: "html",
    url: "https://www.csis.org/programs/middle-east-program",
    lang: "en",
    regionFocus: "mena",
    base: "outside",
    category: "think-tank",
    freq: "periodic",
    topics: ["security", "geopolitics", "politics"],
    focusKeywords: ["middle east", "gulf", "iran", "arab"]
  },
  {
    name: "IFRI Middle East and North Africa",
    nameAr: "المعهد الفرنسي - الشرق الأوسط وشمال أفريقيا",
    method: "html",
    url: "https://www.ifri.org/fr/recherche/zones-geographiques/moyen-orient-maghreb",
    lang: "fr",
    regionFocus: "mena",
    base: "outside",
    category: "think-tank",
    freq: "periodic",
    topics: ["geopolitics", "security", "economy"],
    focusKeywords: ["moyen-orient", "maghreb", "monde arabe"]
  },
  {
    name: "IRIS Middle East / North Africa",
    nameAr: "IRIS - الشرق الأوسط وشمال أفريقيا",
    method: "html",
    url: "https://www.iris-france.org/geopolitique-et-strategie/moyen-orient/",
    lang: "fr",
    regionFocus: "mena",
    base: "outside",
    category: "think-tank",
    freq: "periodic",
    topics: ["geopolitics", "politics", "security"],
    focusKeywords: ["moyen-orient", "maghreb", "afrique du nord"]
  },

  // =========================================================
  // 4) OUTSIDE REGION BUT FOCUSED ON AFRICA / AFRICAN STUDIES
  // =========================================================
  {
    name: "Cambridge Centre of African Studies",
    nameAr: "مركز كامبريدج للدراسات الأفريقية",
    method: "html",
    url: "https://www.african.cam.ac.uk/books",
    lang: "en",
    regionFocus: "africa",
    base: "outside",
    category: "university-center",
    freq: "periodic",
    topics: ["culture", "history", "politics", "society"],
    focusKeywords: ["africa", "african studies", "book series"]
  },
  {
    name: "Oxford African Studies Centre",
    nameAr: "مركز أكسفورد للدراسات الأفريقية",
    method: "html",
    url: "https://www.africanstudies.ox.ac.uk/publications",
    lang: "en",
    regionFocus: "africa",
    base: "outside",
    category: "university-center",
    freq: "periodic",
    topics: ["history", "culture", "politics", "economy"],
    focusKeywords: ["africa", "african studies"]
  },
  {
    name: "Edinburgh Centre of African Studies",
    nameAr: "مركز إدنبرة للدراسات الأفريقية",
    method: "html",
    url: "https://www.cas.ed.ac.uk/publications",
    lang: "en",
    regionFocus: "africa",
    base: "outside",
    category: "university-center",
    freq: "periodic",
    topics: ["society", "culture", "politics"],
    focusKeywords: ["africa", "african studies"]
  },
  {
    name: "Harvard Center for African Studies",
    nameAr: "مركز هارفارد للدراسات الأفريقية",
    method: "html",
    url: "https://africa.harvard.edu/publications",
    lang: "en",
    regionFocus: "africa",
    base: "outside",
    category: "university-center",
    freq: "periodic",
    topics: ["society", "culture", "politics", "economy"],
    focusKeywords: ["africa", "african studies"]
  },
  {
    name: "Stanford Center for African Studies",
    nameAr: "مركز ستانفورد للدراسات الأفريقية",
    method: "html",
    url: "https://cas.stanford.edu/publications",
    lang: "en",
    regionFocus: "africa",
    base: "outside",
    category: "university-center",
    freq: "periodic",
    topics: ["culture", "society", "politics"],
    focusKeywords: ["africa", "african studies"]
  },
  {
    name: "Northwestern Program of African Studies",
    nameAr: "برنامج نورث وسترن للدراسات الأفريقية",
    method: "html",
    url: "https://www.africanstudies.northwestern.edu/about/publications.html",
    lang: "en",
    regionFocus: "africa",
    base: "outside",
    category: "university-center",
    freq: "periodic",
    topics: ["culture", "history", "society"],
    focusKeywords: ["africa", "african studies"]
  },
  {
    name: "GIGA Institute for African Affairs",
    nameAr: "معهد GIGA للشؤون الأفريقية",
    method: "html",
    url: "https://www.giga-hamburg.de/en/the-giga/institutes/giga-institute-for-african-affairs",
    lang: "en",
    regionFocus: "africa",
    base: "outside",
    category: "research-center",
    freq: "periodic",
    topics: ["politics", "economy", "governance", "society"],
    focusKeywords: ["africa", "sub-saharan africa", "african politics"]
  },
  {
    name: "Nordic Africa Institute",
    nameAr: "المعهد الإسكندنافي لأفريقيا",
    method: "html",
    url: "https://nai.uu.se/publications/",
    lang: "en",
    regionFocus: "africa",
    base: "outside",
    category: "research-center",
    freq: "periodic",
    topics: ["culture", "society", "governance", "economy"],
    focusKeywords: ["africa", "african studies", "society"]
  },
  {
    name: "Brookings Africa Growth Initiative",
    nameAr: "بروكينغز - مبادرة النمو الأفريقي",
    method: "html",
    url: "https://www.brookings.edu/series/africa-growth-initiative/",
    lang: "en",
    regionFocus: "africa",
    base: "outside",
    category: "think-tank",
    freq: "periodic",
    topics: ["economy", "governance", "development"],
    focusKeywords: ["africa", "african growth", "development"]
  },
  {
    name: "Foresight Africa",
    nameAr: "فورسايت أفريقيا",
    method: "html",
    url: "https://www.brookings.edu/collection/foresight-africa-2025-2030/",
    lang: "en",
    regionFocus: "africa",
    base: "outside",
    category: "think-tank",
    freq: "annual",
    topics: ["economy", "governance", "politics", "climate"],
    focusKeywords: ["africa", "foresight africa"]
  },
  {
    name: "Africa Center for Strategic Studies",
    nameAr: "مركز أفريقيا للدراسات الاستراتيجية",
    method: "html",
    url: "https://africacenter.org/publications-en/",
    lang: "en",
    regionFocus: "africa",
    base: "outside",
    category: "think-tank",
    freq: "periodic",
    topics: ["security", "governance", "peace"],
    focusKeywords: ["africa", "security", "sahel", "horn of africa"]
  },
  {
    name: "Chatham House Africa Programme",
    nameAr: "تشاتام هاوس - برنامج أفريقيا",
    method: "html",
    url: "https://www.chathamhouse.org/regions/africa",
    lang: "en",
    regionFocus: "africa",
    base: "outside",
    category: "think-tank",
    freq: "periodic",
    topics: ["governance", "economy", "international", "security"],
    focusKeywords: ["africa", "sahel", "horn of africa", "sub-saharan"]
  },
  {
    name: "CSIS Africa Program",
    nameAr: "CSIS - برنامج أفريقيا",
    method: "html",
    url: "https://www.csis.org/programs/africa-program",
    lang: "en",
    regionFocus: "africa",
    base: "outside",
    category: "think-tank",
    freq: "periodic",
    topics: ["security", "economy", "geopolitics"],
    focusKeywords: ["africa", "sahel", "east africa", "west africa"]
  },
  {
    name: "IFRI Sub-Saharan Africa",
    nameAr: "المعهد الفرنسي - أفريقيا جنوب الصحراء",
    method: "html",
    url: "https://www.ifri.org/fr/recherche/zones-geographiques/afrique-subsaharienne",
    lang: "fr",
    regionFocus: "africa",
    base: "outside",
    category: "think-tank",
    freq: "periodic",
    topics: ["geopolitics", "security", "economy"],
    focusKeywords: ["afrique", "sahel", "afrique subsaharienne"]
  },
  {
    name: "LAM - Les Afriques dans le Monde",
    nameAr: "معهد أفريقيا في العالم",
    method: "html",
    url: "https://lam.sciencespobordeaux.fr/publications",
    lang: "fr",
    regionFocus: "africa",
    base: "outside",
    category: "university-center",
    freq: "periodic",
    topics: ["politics", "society", "culture", "history"],
    focusKeywords: ["afrique", "politique", "société"]
  },
  {
    name: "IMAF - Institut des Mondes Africains",
    nameAr: "معهد العوالم الأفريقية",
    method: "html",
    url: "https://imaf.cnrs.fr/spip.php?rubrique21",
    lang: "fr",
    regionFocus: "africa",
    base: "outside",
    category: "research-center",
    freq: "periodic",
    topics: ["history", "culture", "society"],
    focusKeywords: ["afrique", "histoire", "société", "culture"]
  },

  // =========================================================
  // 5) GLOBAL / SELECTIVE FEEDS TO FILTER BY MENA-AFRICA KEYWORDS
  // =========================================================
  {
    name: "Brookings General Feed",
    nameAr: "بروكينغز",
    method: "rss",
    url: "https://www.brookings.edu/feed/",
    lang: "en",
    regionFocus: "global",
    base: "outside",
    category: "think-tank",
    freq: "periodic",
    topics: ["politics", "economy", "governance", "society"],
    focusKeywords: ["middle east", "arab", "africa", "sahel", "north africa", "gulf"]
  },
  {
    name: "Carnegie Endowment",
    nameAr: "مؤسسة كارنيغي",
    method: "rss",
    url: "https://carnegieendowment.org/rss/solr.xml",
    lang: "en",
    regionFocus: "global",
    base: "outside",
    category: "think-tank",
    freq: "periodic",
    topics: ["politics", "governance", "geopolitics"],
    focusKeywords: ["middle east", "arab", "africa", "sahel", "north africa"]
  },
  {
    name: "ECFR",
    nameAr: "المجلس الأوروبي للعلاقات الخارجية",
    method: "rss",
    url: "https://ecfr.eu/feed/",
    lang: "en",
    regionFocus: "global",
    base: "outside",
    category: "think-tank",
    freq: "periodic",
    topics: ["geopolitics", "international", "security"],
    focusKeywords: ["middle east", "arab", "africa", "sahel", "maghreb"]
  },
  {
    name: "Stimson Center",
    nameAr: "مركز ستيمسون",
    method: "rss",
    url: "https://www.stimson.org/feed/",
    lang: "en",
    regionFocus: "global",
    base: "outside",
    category: "think-tank",
    freq: "periodic",
    topics: ["security", "peace", "governance"],
    focusKeywords: ["middle east", "africa", "sahel", "sudan", "horn of africa"]
  },
  {
    name: "SIPRI",
    nameAr: "معهد ستوكهولم لأبحاث السلام",
    method: "rss",
    url: "https://www.sipri.org/rss.xml",
    lang: "en",
    regionFocus: "global",
    base: "outside",
    category: "think-tank",
    freq: "periodic",
    topics: ["security", "peace", "arms", "geopolitics"],
    focusKeywords: ["middle east", "africa", "north africa", "sahel", "sudan"]
  },
  {
    name: "RAND Research Reports",
    nameAr: "تقارير راند البحثية",
    method: "rss",
    url: "https://www.rand.org/pubs/research_reports.xml",
    lang: "en",
    regionFocus: "global",
    base: "outside",
    category: "think-tank",
    freq: "periodic",
    topics: ["security", "economy", "public-policy"],
    focusKeywords: ["middle east", "arab", "africa", "north africa"]
  },
  {
    name: "PRIO",
    nameAr: "معهد أوسلو لأبحاث السلام",
    method: "rss",
    url: "https://www.prio.org/rss",
    lang: "en",
    regionFocus: "global",
    base: "outside",
    category: "research-center",
    freq: "periodic",
    topics: ["peace", "security", "conflict"],
    focusKeywords: ["middle east", "africa", "sahel", "sudan", "horn of africa"]
  },
  {
    name: "Egmont Institute",
    nameAr: "معهد إيغمونت",
    method: "rss",
    url: "https://www.egmontinstitute.be/feed/",
    lang: "en",
    regionFocus: "global",
    base: "outside",
    category: "think-tank",
    freq: "periodic",
    topics: ["security", "governance", "international"],
    focusKeywords: ["middle east", "africa", "north africa", "sahel"]
  },
  {
    name: "Clingendael",
    nameAr: "معهد كلينغندال",
    method: "rss",
    url: "https://www.clingendael.org/rss.xml",
    lang: "en",
    regionFocus: "global",
    base: "outside",
    category: "think-tank",
    freq: "periodic",
    topics: ["security", "international", "migration"],
    focusKeywords: ["middle east", "africa", "sahel", "migration", "north africa"]
  },
  {
    name: "SWP Berlin Feed",
    nameAr: "المعهد الألماني للشؤون الدولية والسياسة",
    method: "rss",
    url: "https://www.swp-berlin.org/en/rss",
    lang: "en",
    regionFocus: "global",
    base: "outside",
    category: "think-tank",
    freq: "periodic",
    topics: ["geopolitics", "security", "politics"],
    focusKeywords: ["middle east", "africa", "arab", "gulf", "sahel"]
  },

  // =========================================================
  // 6) IGO / IFI / NGO RESEARCH SOURCES WITH STRONG MENA-AFRICA COVERAGE
  // =========================================================
  {
    name: "ESCWA Publications",
    nameAr: "منشورات الإسكوا",
    method: "html",
    url: "https://www.unescwa.org/publications",
    lang: "en",
    regionFocus: "mena",
    base: "outside",
    category: "igo",
    freq: "periodic",
    topics: ["economy", "governance", "development", "society"],
    focusKeywords: ["arab region", "middle east", "western asia", "المنطقة العربية"]
  },
  {
    name: "ESCWA Arabic Publications",
    nameAr: "منشورات الإسكوا بالعربية",
    method: "html",
    url: "https://www.unescwa.org/ar/publications",
    lang: "ar",
    regionFocus: "mena",
    base: "outside",
    category: "igo",
    freq: "periodic",
    topics: ["economy", "governance", "development"],
    focusKeywords: ["المنطقة العربية", "الدول العربية", "غرب آسيا"]
  },
  {
    name: "UNECA Publications",
    nameAr: "منشورات اللجنة الاقتصادية لأفريقيا",
    method: "html",
    url: "https://www.uneca.org/publications",
    lang: "en",
    regionFocus: "africa",
    base: "outside",
    category: "igo",
    freq: "periodic",
    topics: ["economy", "governance", "development"],
    focusKeywords: ["africa", "african", "economic report on africa"]
  },
  {
    name: "UNECA French Publications",
    nameAr: "منشورات اللجنة الاقتصادية لأفريقيا بالفرنسية",
    method: "html",
    url: "https://www.uneca.org/fr/publications",
    lang: "fr",
    regionFocus: "africa",
    base: "outside",
    category: "igo",
    freq: "periodic",
    topics: ["economy", "governance", "development"],
    focusKeywords: ["afrique", "rapport économique sur l'afrique"]
  },
  {
    name: "AfDB Publications",
    nameAr: "منشورات البنك الأفريقي للتنمية",
    method: "html",
    url: "https://www.afdb.org/en/documents/publications",
    lang: "en",
    regionFocus: "africa",
    base: "outside",
    category: "ifi",
    freq: "periodic",
    topics: ["economy", "development", "governance"],
    focusKeywords: ["africa", "african economic outlook"]
  },
  {
    name: "AfDB French Publications",
    nameAr: "منشورات البنك الأفريقي للتنمية بالفرنسية",
    method: "html",
    url: "https://www.afdb.org/fr/documents/publications",
    lang: "fr",
    regionFocus: "africa",
    base: "outside",
    category: "ifi",
    freq: "periodic",
    topics: ["economy", "development", "governance"],
    focusKeywords: ["afrique", "perspectives économiques"]
  },
  {
    name: "IMF MENA Regional Economic Outlook",
    nameAr: "صندوق النقد - آفاق الشرق الأوسط",
    method: "html",
    url: "https://www.imf.org/en/Publications/REO/MECA",
    lang: "en",
    regionFocus: "mena",
    base: "outside",
    category: "ifi",
    freq: "semi",
    topics: ["economy", "governance"],
    focusKeywords: ["middle east", "north africa", "meca", "arab"]
  },
  {
    name: "IMF SSA Regional Economic Outlook",
    nameAr: "صندوق النقد - آفاق أفريقيا جنوب الصحراء",
    method: "html",
    url: "https://www.imf.org/en/Publications/REO/SSA",
    lang: "en",
    regionFocus: "africa",
    base: "outside",
    category: "ifi",
    freq: "semi",
    topics: ["economy", "governance"],
    focusKeywords: ["sub-saharan africa", "africa", "ssa"]
  },
  {
    name: "World Bank MENA",
    nameAr: "البنك الدولي - الشرق الأوسط وشمال أفريقيا",
    method: "html",
    url: "https://www.worldbank.org/en/region/mena/publication",
    lang: "en",
    regionFocus: "mena",
    base: "outside",
    category: "ifi",
    freq: "periodic",
    topics: ["economy", "development", "governance"],
    focusKeywords: ["middle east", "north africa", "mena"]
  },
  {
    name: "World Bank Africa",
    nameAr: "البنك الدولي - أفريقيا",
    method: "html",
    url: "https://www.worldbank.org/en/region/afr/publication",
    lang: "en",
    regionFocus: "africa",
    base: "outside",
    category: "ifi",
    freq: "periodic",
    topics: ["economy", "development", "governance"],
    focusKeywords: ["africa", "sub-saharan africa"]
  },
  {
    name: "Human Rights Watch Publications",
    nameAr: "هيومن رايتس ووتش - منشورات",
    method: "rss",
    url: "https://www.hrw.org/rss/publications",
    lang: "en",
    regionFocus: "global",
    base: "outside",
    category: "ngo",
    freq: "periodic",
    topics: ["rights", "politics", "governance"],
    focusKeywords: ["middle east", "north africa", "africa", "sudan", "gaza", "sahel"]
  },
  {
    name: "Amnesty International",
    nameAr: "العفو الدولية",
    method: "rss",
    url: "https://www.amnesty.org/en/feed/",
    lang: "en",
    regionFocus: "global",
    base: "outside",
    category: "ngo",
    freq: "periodic",
    topics: ["rights", "governance"],
    focusKeywords: ["middle east", "north africa", "africa", "arab", "sahel"]
  },
  {
    name: "RSF",
    nameAr: "مراسلون بلا حدود",
    method: "rss",
    url: "https://rsf.org/en/rss.xml",
    lang: "en",
    regionFocus: "global",
    base: "outside",
    category: "ngo",
    freq: "periodic",
    topics: ["rights", "media", "governance"],
    focusKeywords: ["middle east", "africa", "north africa", "arab"]
  },
  {
    name: "IDEA",
    nameAr: "المعهد الدولي للديمقراطية",
    method: "rss",
    url: "https://www.idea.int/rss.xml",
    lang: "en",
    regionFocus: "global",
    base: "outside",
    category: "ngo",
    freq: "periodic",
    topics: ["governance", "politics", "democracy"],
    focusKeywords: ["middle east", "africa", "arab", "democracy"]
  },
  {
    name: "GI-TOC",
    nameAr: "المبادرة العالمية ضد الجريمة المنظمة",
    method: "rss",
    url: "https://globalinitiative.net/feed/",
    lang: "en",
    regionFocus: "global",
    base: "outside",
    category: "ngo",
    freq: "periodic",
    topics: ["security", "governance", "crime"],
    focusKeywords: ["africa", "sahel", "middle east", "north africa"]
  }
];

export const POSITIVE_KEYWORDS = [
  "report","study","paper","brief","analysis","assessment","survey","outlook","index",
  "yearbook","monitor","review","working paper","discussion paper","policy paper",
  "research paper","special report","issue brief","dispatch","monograph","booklet",
  "rapport","étude","note d'analyse","cahier","bilan","aperçu","working papers",
  "تقرير","دراسة","ورقة بحثية","ورقة سياسات","إحاطة","تحليل","مؤشر","استعراض","ورقة عمل"
];

export const NEGATIVE_KEYWORDS = [
  "press release","press statement","news","commentary","op-ed","podcast","video","webinar",
  "speech","remarks","newsletter","event","announcement","press office",
  "communiqué de presse","déclaration","discours","actualité",
  "بيان صحفي","خبر","تصريح","ندوة","فعالية","إعلان","تغطية"
];

export const MENA_KEYWORDS = [
  "middle east","mena","arab","arab world","gulf","maghreb","levant","north africa",
  "palestine","gaza","iraq","syria","lebanon","jordan","egypt","libya","morocco",
  "tunisia","algeria","saudi","uae","qatar","oman","kuwait","bahrain","yemen",
  "الشرق الأوسط","العالم العربي","الخليج","المغرب العربي","المشرق","فلسطين","غزة",
  "العراق","سوريا","لبنان","الأردن","مصر","ليبيا","المغرب","تونس","الجزائر","السعودية"
];

export const AFRICA_KEYWORDS = [
  "africa","african","sahel","sub-saharan","horn of africa","east africa","west africa",
  "north africa","southern africa","nigeria","kenya","ethiopia","sudan","south africa",
  "ghana","senegal","congo","cameroon","uganda","tanzania","mali","niger","chad",
  "afrique","africain","sahel","corne de l'afrique",
  "أفريقيا","إفريقي","الساحل","القرن الأفريقي","غرب أفريقيا","شرق أفريقيا"
];
